version: "3.7"

services:
  ldp-consumer:
    build:
      context: ./ldp-microservice
      dockerfile: Dockerfile
    command:
      [
        "./wait-for-it.sh",
        "rabbitmq:5672",
        "--",
        "nodemon",
        "bin/ldp-consumer",
        start",
      ]
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    volumes:
      - ./ldp-microservice:/usr/src/app
      - /usr/src/app/node_modules/
      - static-data:/usr/src/app/data

  ldp-web:
    build:
      context: ./ldp-microservice
      dockerfile: Dockerfile
    command: nodemon bin/ldp-web start
    ports:
      - "8442:8442"
    environment:
      DEBUG: ldp:*
      ADD_FLAGS: --no-reject-unauthorized
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      SOLID_ID_URI: https://solid-id:8443
      SOLID_SSL_KEY: ../privkey.pem
      SOLID_SSL_CERT: ../fullchain.pem
      SOLID_SERVER_URI: https://localhost:8442
      SOLID_PORT: 8442
    volumes:
      - ./ldp-microservice:/usr/src/app
      - /usr/src/app/node_modules/
      - static-data:/usr/src/app/data

  solid-id:
    build:
      context: ./solid-id
      dockerfile: Dockerfile
    command:
      [
        "./wait-for-it.sh",
        "rabbitmq:5672",
        "--",
        "nodemon",
        "bin/solid",
        "start",
      ]
    ports:
      - "8443:8443"
    environment:
      DEBUG: solid:*
      ADD_FLAGS: --no-reject-unauthorized
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      SOLID_SSL_KEY: ../privkey.pem
      SOLID_SSL_CERT: ../fullchain.pem
      SOLID_SERVER_URI: https://localhost:8443
      SOLID_PORT: 8443
    volumes:
      - ./solid-id:/usr/src/app
      - /usr/src/app/node_modules/
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3

volumes:
  static-data:
