version: "3.7"

services:
  ldp-consumer:
    build:
      context: ./ldp-microservice
      dockerfile: Dockerfile
    command:
      [
        "./wait-for-it.sh",
        "rabbitmq:5672",
        "--",
        "node",
        "bin/ldp-consumer",
        start",
      ]
    depends_on:
      - rabbitmq
    links:
      - "solid-id-web:solid-id.com"
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      SOLID_ID_URI: https://solid-id.com:8443
      SOLID_SSL_KEY: ../privkey.pem
      SOLID_SSL_CERT: ../fullchain.pem
      SOLID_SERVER_URI: https://solid.com:8442
      SOLID_PORT: 8442
    volumes:
      - ./data:/usr/src/app/data

  ldp-web:
    build:
      context: ./ldp-microservice
      dockerfile: Dockerfile
    command: node bin/ldp-web start
    ports:
      - "8442:8442"
    environment:
      DEBUG: ldp:*
      ADD_FLAGS: --no-reject-unauthorized
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      SOLID_ID_URI: https://solid-id.com:8443
      SOLID_SSL_KEY: ../privkey.pem
      SOLID_SSL_CERT: ../fullchain.pem
      SOLID_SERVER_URI: https://solid.com:8442
      SOLID_PORT: 8442
    volumes:
      - ./data:/usr/src/app/data
    links:
      - "solid-id-web:solid-id.com"

  solid-id-web:
    build:
      context: ./solid-id
      dockerfile: Dockerfile
    command:
      [
        "./wait-for-it.sh",
        "rabbitmq:5672",
        "--",
        "node",
        "bin/solid",
        "start",
      ]
    ports:
      - "8443:8443"
    environment:
      DEBUG: solid:*
      ADD_FLAGS: --no-reject-unauthorized
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      SOLID_SSL_KEY: ../privkey.pem
      SOLID_SSL_CERT: ../fullchain.pem
      SOLID_SERVER_URI: https://solid-id.com:8443
      SOLID_PORT: 8443
      SOLID_GATEWAY_URI: https://solid.com:8442
    volumes:
      - ./store:/usr/src/app/.db
    depends_on:
      - rabbitmq

  solid-id-consumer:
    build:
      context: ./solid-id
      dockerfile: Dockerfile
    command:
      [
        "./wait-for-it.sh",
        "rabbitmq:5672",
        "--",
        "node",
        "bin/solid-consumer.js"
      ]
    environment:
      DEBUG: solid:*
      ADD_FLAGS: --no-reject-unauthorized
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      SOLID_SSL_KEY: ../privkey.pem
      SOLID_SSL_CERT: ../fullchain.pem
      SOLID_SERVER_URI: https://solid-id.com:8443
      SOLID_PORT: 8443
      SOLID_GATEWAY_URI: https://solid.com:8442
    volumes:
      - ./store:/usr/src/app/.db
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  accounts-web:
    build:
      context: ./accounts-web
      dockerfile: Dockerfile
    command:
      [
        "./wait-for-it.sh",
        "rabbitmq:5672",
        "--",
        "npm",
        "run",
        "start",
      ]
    ports:
      - "8441:8441"
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

  api-gw:
    build:
      context: ./api-gw
      dockerfile: Dockerfile
    command: 'npm run start'
    ports:
      - "9000:9000"
    environment:
      ACCOUNTS_WEB_HOST: accounts-web
      ACCOUNTS_WEB_PORT: 8441
      LDP_HOST: ldp.solid.pedropiloto.com
      LDP_PORT: 8442
    depends_on:
      - accounts-web

  rabbitmq:
    image: rabbitmq:3
