const debug = require('debug')

exports.handlers = debug('ldp:handlers')
exports.errors = debug('ldp:errors')
exports.ACL = debug('ldp:ACL')
exports.parse = debug('ldp:parse')
exports.metadata = debug('ldp:metadata')
exports.authentication = debug('ldp:authentication')
exports.settings = debug('ldp:settings')
exports.server = debug('ldp:server')
exports.subscription = debug('ldp:subscription')
exports.container = debug('ldp:container')
exports.accounts = debug('ldp:accounts')
exports.email = debug('ldp:email')
exports.ldp = debug('ldp:ldp')
exports.fs = debug('ldp:fs')
