# This file is an example for running ldp-web server directly on port 443 with
# existing (letsencrypt) certificates and without reverse proxy.

# To use it adjust any line that is commented with (!):
# 1. Change any occurrence of the domain `ldp-web.example` to your actual domain
# 2. Adjust the `latest` tag to a specific version you want to use.

version: '3.7'
services:
  server:
    image: nodesolidserver/node-solid-server:latest # (!) use specific version tag here

    # this ensures automatic container start, when host reboots
    restart: always

    ports:
      - 443:8443

    volumes:
      # mount local directories to the container
      # (!) the host directories have to exist and be owned by UID 1000
      - /opt/ldp-web/data:/opt/ldp-web/data
      - /opt/ldp-web/.db:/opt/ldp-web/.db
      - /opt/ldp-web/config:/opt/ldp-web/config

      # (!) mount existing TLS certificates, e.g. from letsencrypt
      # (!) ensure that the key and fullchain files are readable by UID 1000
      - /etc/letsencrypt/live/ldp-web.example/:/opt/ldp-web/certs

    environment:
      # (!) use your actual SOLID_SERVER_URI
      - "SOLID_SERVER_URI=https://ldp-web.example"
      - "SOLID_SSL_KEY=/opt/ldp-web/certs/key.pem"
      - "SOLID_SSL_CERT=/opt/ldp-web/certs/fullchain.pem"